csv_write_test – fortran-csv-module
csv_write_test Subroutine
30 statements
Source File
subroutine csv_write_test()
Arguments
None
Calls
Called by
Source Code
        subroutine csv_write_test()
        implicit none
        type(csv_file) :: f
        logical :: status_ok
        write(*,*) ''
        write(*,*) '============================'
        write(*,*) ' csv_write_test '
        write(*,*) '============================'
        write(*,*) ''
        ! open the file
        call f%open('test_write.csv',n_cols=4,status_ok=status_ok)
        if (status_ok) then
            ! add header
            call f%add(['x','y','z','t'])
            call f%next_row()
            ! add some data:
            call f%add([1.0_wp,2.0_wp,3.0_wp],real_fmt='(F5.3)')
            call f%add(.true.)
            call f%next_row()
            call f%add([4.0_wp,5.0_wp,6.0_wp],real_fmt='(F5.3)')
            call f%add(.false.)
            call f%next_row()
            call f%add([1.5_sp,2.5_sp,3.5_sp],real_fmt='(F5.3)')
            call f%add(.true.)
            call f%next_row()
            call f%add([4.5_sp,5.5_sp,6.5_sp],real_fmt='(F5.3)')
            call f%add(.false.)
            call f%next_row()
            ! finished
            call f%close(status_ok)
        else
            error stop 'could not open file'
        end if
        end subroutine csv_write_test
Call graph
csv_write_test calls add, next_row
add_matrix calls add, next_row
add_vector calls add
csv_test calls csv_write_test