csv_read_test – fortran-csv-module
csv_read_test Subroutine
39 statements
Source File
subroutine csv_read_test()
Arguments
None
Calls
Called by
Source Code
        subroutine csv_read_test()
        implicit none
        type(csv_file) :: f
        character(len=30),dimension(:),allocatable :: header
        real(wp),dimension(:),allocatable :: x,y,z
        real(sp),dimension(:),allocatable :: u,v,w
        logical,dimension(:),allocatable :: t
        logical :: status_ok
        integer,dimension(:),allocatable :: itypes
        write(*,*) ''
        write(*,*) '============================'
        write(*,*) ' csv_read_test '
        write(*,*) '============================'
        write(*,*) ''
        ! read the file
        call f%read('test_write.csv',header_row=1,status_ok=status_ok)
        if (status_ok) then
            ! get the header and type info
            call f%get_header(header,status_ok)
            call f%variable_types(itypes,status_ok)
            ! get some data
            call f%get(1,x,status_ok)
            call f%get(2,y,status_ok)
            call f%get(3,z,status_ok)
            call f%get(4,t,status_ok)
            write(*,*) 'x=',x
            write(*,*) 'y=',y
            write(*,*) 'z=',z
            write(*,*) 't=',t
            call f%get(1,u,status_ok)
            call f%get(2,v,status_ok)
            call f%get(3,w,status_ok)
            call f%get(4,t,status_ok)
            write(*,*) 'x=',u
            write(*,*) 'y=',v
            write(*,*) 'z=',w
            write(*,*) 't=',t
            ! destroy the file
            call f%destroy()
        else
            error stop 'could not open file'
        end if
        end subroutine csv_read_test
Call graph
csv_read_test calls get, get_header, destroy_csv_file, variable_types
variable_types calls infer_variable_type
csv_get_value calls to_integer, to_logical, to_real_sp, to_real_wp
get_character_column calls get_column
get_csv_string_column calls get_column
get_integer_column calls get_column
get_logical_column calls get_column
get_real_sp_column calls get_column
get_real_wp_column calls get_column
infer_variable_type calls to_integer, to_logical, to_real_wp
get_column calls csv_get_value
to_logical calls lowercase_string
csv_test calls csv_read_test