destroy_csv_file – fortran-csv-module
destroy_csv_file Subroutine
4 statements
Source File
private subroutine destroy_csv_file(me)
Destroy the data in a CSV file.
Type Bound
csv_file
Arguments
Type Intent Optional Attributes Name
class(csv_file), intent(out) :: me
Called by
Source Code
    subroutine destroy_csv_file(me)
    implicit none
    class(csv_file),intent(out) :: me
    end subroutine destroy_csv_file
Call graph
csv_read_test calls destroy_csv_file
open_csv_file calls destroy_csv_file
read_csv_file calls destroy_csv_file
csv_test3 calls destroy_csv_file
csv_test calls csv_read_test