get_csv_string_column – csv-fortran
get_csv_string_column Subroutine
14 statements
Source File
private subroutine get_csv_string_column(me, icol, r, status_ok)
Convert a column from a csv_string matrix to a type(csv_string) vector.
Type Bound
csv_file
Arguments
Type Intent Optional Attributes Name
class(csv_file), intent(inout) :: me
integer, intent(in) :: icol
column number
type(csv_string), intent(out), dimension(:), allocatable :: r
logical, intent(out) :: status_ok
Calls
Source Code
    subroutine get_csv_string_column(me,icol,r,status_ok)
    implicit none
    class(csv_file),intent(inout) :: me
    integer,intent(in) :: icol  !! column number
    type(csv_string),dimension(:),allocatable,intent(out) :: r
    logical,intent(out) :: status_ok
    if (allocated(me%csv_data)) then
        allocate(r(me%n_rows))  ! size the output vector
        call me%get_column(icol,r,status_ok)
    else
        if (me%verbose) write(error_unit,'(A,1X,I5)') 'Error: class has not been initialized'
        status_ok = .false.
    end if
    end subroutine get_csv_string_column
Call graph
get_csv_string_column calls get_column
get_column calls csv_get_value
csv_get_value calls to_integer, to_logical, to_real_sp, to_real_wp
to_logical calls lowercase_string