get_header_str – fortran-csv-module
get_header_str Subroutine
17 statements
Source File
private subroutine get_header_str(me, header, status_ok)
Returns the header as a character(len=*) array. (read must have already been called to read the file).
Type Bound
csv_file
Arguments
Type Intent Optional Attributes Name
class(csv_file), intent(inout) :: me
character(len=*), intent(out), dimension(:), allocatable :: header
logical, intent(out) :: status_ok
Called by
Source Code
    subroutine get_header_str(me,header,status_ok)
    implicit none
    class(csv_file),intent(inout) :: me
    character(len=*),dimension(:),allocatable,intent(out) :: header
    logical,intent(out) :: status_ok
    integer :: i !! column counter
    if (allocated(me%header)) then
        allocate(header(me%n_cols))
        do i=1,me%n_cols
            header(i) = me%header(i)%str
        end do
        status_ok = .true.
    else
        if (me%verbose) write(error_unit,'(A)') 'Error: no header in class.'
        status_ok = .false.
    end if
    end subroutine get_header_str
Call graph
csv_read_test calls get_header
csv_test_1 calls get_header
csv_test3 calls get_header
csv_test calls csv_read_test, csv_test_1