lowercase_string – fortran-csv-module
lowercase_string Function
12 statements
Source File
public pure function lowercase_string(str) result(s_lower)
Returns lowercase version of the string.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
input string
Return Value character(len=len=(len(str)))
lowercase version of the string
Called by
Source Code
    pure function lowercase_string(str) result(s_lower)
    implicit none
    character(len=*),intent(in) :: str      !! input string
    character(len=(len(str)))   :: s_lower  !! lowercase version of the string
    integer :: i  !! counter
    integer :: j  !! index of uppercase character
    s_lower = str
    do i = 1, len_trim(str)
        j = index(upper,s_lower(i:i))
        if (j>0) s_lower(i:i) = lower(j:j)
    end do
    end function lowercase_string
Call graph
to_logical calls lowercase_string
csv_get_value calls to_logical
infer_variable_type calls to_logical
get_column calls csv_get_value
variable_types calls infer_variable_type
csv_read_test calls get, variable_types
csv_test_1 calls get, variable_types
get_character_column calls get_column
get_csv_string_column calls get_column
get_integer_column calls get_column
get_logical_column calls get_column
get_real_sp_column calls get_column
get_real_wp_column calls get_column
csv_test3 calls get
csv_test calls csv_read_test, csv_test_1