swap – csv-fortran
swap Subroutine
9 statements
Source File
private pure elemental subroutine swap(i1, i2)
Swap two integer values.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: i1
integer, intent(inout) :: i2
Called by
Source Code
    pure elemental subroutine swap(i1,i2)
    implicit none
    integer,intent(inout) :: i1
    integer,intent(inout) :: i2
    integer :: tmp
    tmp = i1
    i1  = i2
    i2  = tmp
    end subroutine swap
Call graph
sort_ascending calls swap
unique calls sort_ascending
read_csv_file calls unique