to_logical – fortran-csv-module
to_logical Subroutine
20 statements
Source File
private pure elemental subroutine to_logical(str, val, status_ok)
Convert a string to a logical
Evaluates to .true. for strings ['1','t','true','.true.']
Evaluates to .false. for strings ['0','f','false','.false.']
The string match is not case sensitive.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
logical, intent(out) :: val
logical, intent(out) :: status_ok
Calls
Called by
Source Code
    pure elemental subroutine to_logical(str,val,status_ok)
    implicit none
    character(len=*),intent(in) :: str
    logical,intent(out) :: val
    logical,intent(out) :: status_ok
    character(len=:),allocatable :: tmp
    ! True and False options (all lowercase):
    character(len=*),dimension(4),parameter :: true_str  = ['1     ',&
                                                            't     ',&
                                                            'true  ',&
                                                            '.true.']
    character(len=*),dimension(4),parameter :: false_str = ['0      ',&
                                                            'f      ',&
                                                            'false  ',&
                                                            '.false.']
    tmp = lowercase_string(str)
    if ( any(tmp==true_str) ) then
        val = .true.
        status_ok = .true.
    else if ( any(tmp==false_str) ) then
        val = .false.
        status_ok = .true.
    else
        val = .false.
        status_ok = .false.
    end if
    end subroutine to_logical
Call graph
to_logical calls lowercase_string
csv_get_value calls to_logical
infer_variable_type calls to_logical
get_column calls csv_get_value
variable_types calls infer_variable_type
csv_read_test calls get, variable_types
csv_test_1 calls get, variable_types
get_character_column calls get_column
get_csv_string_column calls get_column
get_integer_column calls get_column
get_logical_column calls get_column
get_real_sp_column calls get_column
get_real_wp_column calls get_column
csv_test3 calls get
csv_test calls csv_read_test, csv_test_1