to_real_sp – fortran-csv-module
to_real_sp Subroutine
14 statements
Source File
private pure elemental subroutine to_real_sp(str, val, status_ok)
Convert a string to a real(sp)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=sp), intent(out) :: val
logical, intent(out) :: status_ok
Called by
Source Code
    pure elemental subroutine to_real_sp(str,val,status_ok)
    implicit none
    character(len=*),intent(in) :: str
    real(sp),intent(out) :: val
    logical,intent(out) :: status_ok
    integer :: istat  !! read `iostat` error code
    read(str,fmt=*,iostat=istat) val
    if (istat==0) then
        status_ok = .true.
    else
        status_ok = .false.
        val = zero
    end if
    end subroutine to_real_sp
Call graph
csv_get_value calls to_real_sp
get_column calls csv_get_value
csv_read_test calls get
csv_test_1 calls get
get_character_column calls get_column
get_csv_string_column calls get_column
get_integer_column calls get_column
get_logical_column calls get_column
get_real_sp_column calls get_column
get_real_wp_column calls get_column
csv_test3 calls get
csv_test calls csv_read_test, csv_test_1