to_real_wp – csv-fortran
to_real_wp Subroutine
14 statements
Source File
private pure elemental subroutine to_real_wp(str, val, status_ok)
Convert a string to a real(wp)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
real(kind=wp), intent(out) :: val
logical, intent(out) :: status_ok
Called by
Source Code
    pure elemental subroutine to_real_wp(str,val,status_ok)
    implicit none
    character(len=*),intent(in) :: str
    real(wp),intent(out) :: val
    logical,intent(out) :: status_ok
    integer :: istat  !! read `iostat` error code
    read(str,fmt=*,iostat=istat) val
    if (istat==0) then
        status_ok = .true.
    else
        status_ok = .false.
        val = zero
    end if
    end subroutine to_real_wp
Call graph
csv_get_value calls to_real_wp
infer_variable_type calls to_real_wp
get_column calls csv_get_value
variable_types calls infer_variable_type
get_character_column calls get_column
get_csv_string_column calls get_column
get_integer_column calls get_column
get_logical_column calls get_column
get_real_sp_column calls get_column
get_real_wp_column calls get_column